version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout
      - run: touch ../hello
      - store_artifacts:
          path: ../hello

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
