version: 2

jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps
      - run: npm i
      - run: npm run test
      - store_artifacts:
          path: index.html
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - .node_modules

  arch-check:
    docker:
      - image: archlinux/base:latest

    steps:
      - run: env

  machine:
    machine: true
    steps:
      - run: env

  remote-docker-check:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - run: env
      - setup_remote_docker
      - run: env
      - run: docker run archlinux/base env

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - arch-check
      - machine
      - remote-docker-check:
          requires:
            - test
            - arch-check
            - machine
